from __future__ import annotations

from typing import Protocol

from ventilation_core.domain.aero import AeroBusState
from ventilation_core.domain.aero_control import AeroControlCommand, AeroControlResult
from ventilation_core.domain.models import FanSetpoints
from ventilation_core.domain.sensors import SensorBusState


class VentilationActuator(Protocol):
    @property
    def ready(self) -> bool: ...

    @property
    def last_error(self) -> str | None: ...

    def apply(self, setpoints: FanSetpoints) -> None: ...

    def stop_all(self) -> None: ...

    def health_check(self) -> None: ...

    def recover(self) -> None: ...

    def close(self) -> None: ...


class SensorBusMonitor(Protocol):
    def state(self) -> SensorBusState: ...

    def health_check(self) -> None: ...

    def close(self) -> None: ...


class AeroBusMonitor(Protocol):
    def state(self) -> AeroBusState: ...

    def execute_control(self, command: AeroControlCommand) -> AeroControlResult: ...

    def health_check(self) -> None: ...

    def close(self) -> None: ...
