plugins {
    id 'com.android.application'
}

android {
    namespace = 'pl.autoklinika.workshopventilation.hmi'

    compileSdk {
        version = release(37) {
            it.minorApiLevel = 0
        }
    }

    defaultConfig {
        applicationId = 'pl.autoklinika.workshopventilation.hmi'
        minSdk = 33
        targetSdk = 33
        versionCode = 3
        versionName = '0.3.0-service-exit-stage3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
